package by.gourianova.binocularvision.controller.command;

public enum CommandName {
	AUTHORIZATION, REGISTRATION, SAVENEWUSER, GOTOINDEXPAGE, GOTOMAINPAGE, GOTOLOGINPAGE,
	LOGOUT, GOTOADMINPAGE, GOTOAPPSPAGE, SHOWALLUSERS, FINDUSER
}
