package by.gourianova.binocularvision.controller.command;

public enum CommandName {
	AUTHORIZATION, REGISTRATION, SAVENEWUSER, GOTOINDEXPAGE, GOTOMAINPAGE, GOTOLOGINPAGE,
	LOGOUT, GOTOADMINPAGE, GOTOAPPSPAGE,
	SHOWALLUSERS, FINDUSER, GOTOUSERSHOWONEPAGE, CHANGEUSERROLE, CHANGEUSERDATA, GOTODELETEUSERPAGE,
	DELETEUSER,
	GOTOUSERCHANGEROLEPAGE,
	GOTOADDROLEPAGE, ADDROLE, SHOWALLROLES,
	SHOWALLORDERS, SHOWUNCLOSEDORDERS, SHOWUSERORDERS,
	GETTYPEDATA, SHOWALLTYPES,
	GETAPPDATA, ADDAPP,
	SHOWALLHTTPADDRESSES, ADDHTTPADDRESS;
}
//,SHOWADMINPAGE,